### ISSUE TITLE
TODO: Test on windows and mac

### ISSUE THREAD

**Issue by elpaso** [akbargumbira/qgis_resources_sharing#10]
Just a reminder

**Comment by akbargumbira** [comment]
I don't have both of them :) But I will try to install windows on vm

**Comment by elpaso** [comment]
@anitagraser can you take care of windows testing? (if yes, please split this ticket win/mac and assign win to you)

**Comment by anitagraser** [comment]
@elpaso I'll test every once in a while, but Akbar will still need to get his Win VM up.

**Comment by akbargumbira** [comment]
yes, I still need to fix those errors, I'm trying to install it again right now..

**Comment by havatv** [comment]
The plugin works on Windows. I close this for now. If someone with a mac has has problems, please open a new issue.
