### ISSUE TITLE
[Windows] Error on resource install: Error: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by anitagraser** [akbargumbira/qgis_resources_sharing#16]
I cannot install resources due to this error.

**Comment by akbargumbira** [comment]
After some checking, I think it's a problem calling subprocess in Windows. Can you try in your QGIS python console this simple script @anitagraser?
```
import subprocess
subprocess.call(['ls', '-l'])
```

@elpaso do you know about this issue?

**Comment by elpaso** [comment]
for windows only, try this: `subprocess.call('dir', shell=True)`
you need a switch for *nix to not add `shell=True`

Where exactly the error comes from?

**Comment by elpaso** [comment]
@akbargumbira can you add a full stack trace in the QGIS logs instead of catching the exception silently?

You should import `traceback` and format the exception, then
```
QgsMessageLog.logMessage(msg, "QGIS Sharing", level=QgsMessageLog.CRITICAL)
```

**Comment by elpaso** [comment]
@akbargumbira , the full stacktrace:

```
Error pulling: [Error 2] The system cannot find the file specified ['Traceback (most recent call last):\n', '  File "C:/Users/boundless/.qgis2/python/plugins\\qgis_symbology_sharing\\symbology_sharing\\repository_handler\\remote_git_handler.py", line 101, in download_collection\n    porcelain.pull(local_repo_dir, self.url.encode(\'utf-8\'), b\'refs/heads/master\')\n', '  File "C:/Users/boundless/.qgis2/python/plugins\\qgis_symbology_sharing\\ext_libs\\dulwich\\porcelain.py", line 619, in pull\n    determine_wants=determine_wants)\n', '  File "C:\\Users\\boundless\\.qgis2\\python\\plugins\\qgis_symbology_sharing\\ext_libs\\dulwich\\client.py", line 251, in fetch\n    progress)\n', '  File "C:\\Users\\boundless\\.qgis2\\python\\plugins\\qgis_symbology_sharing\\ext_libs\\dulwich\\client.py", line 557, in fetch_pack\n    proto, can_read = self._connect(b\'upload-pack\', path)\n', '  File "C:\\Users\\boundless\\.qgis2\\python\\plugins\\qgis_symbology_sharing\\ext_libs\\dulwich\\client.py", line 921, in _connect\n    self.host, argv, port=self.port, username=self.username)\n', '  File "C:\\Users\\boundless\\.qgis2\\python\\plugins\\qgis_symbology_sharing\\ext_libs\\dulwich\\client.py", line 877, in run_command\n    stdout=subprocess.PIPE)\n', '  File "C:\\PROGRA~1\\BOUNDL~1\\Desktop\\osgeo4w\\apps\\Python27\\lib\\subprocess.py", line 711, in __init__\n    errread, errwrite)\n', '  File "C:\\PROGRA~1\\BOUNDL~1\\Desktop\\osgeo4w\\apps\\Python27\\lib\\subprocess.py", line 948, in _execute_child\n    startupinfo)\n', 'WindowsError: [Error 2] The system cannot find the file specified\n']
```

dulwich calls `ssh`, that does not exists on windows.

Are you sure that dulwich **can** run on windows?

**Comment by elpaso** [comment]
Ok, I guess that it falls back to `ssh` because `git` is not installed, checking if installing a git client solves the issue.

**Comment by akbargumbira** [comment]
> @akbargumbira can you add a full stack trace in the QGIS logs instead of catching the exception silently?
> 
> You should import traceback and format the exception, then
> 
> QgsMessageLog.logMessage(msg, "QGIS Sharing", level=QgsMessageLog.CRITICAL)

Ok, I'll add logging


> Are you sure that dulwich can run on windows?

I didn't try it on windows. But I am checking it now (it's quite a struggle to work on window's virtualbox since it's very slow)

**Comment by elpaso** [comment]
I'm tracking down the issue:
- dulwich can probably work on windows provided that `git` is available
- I installed `git` from the official source (all default accepted) but it's not in the path:

From windows command prompt:
```
>where git
C:\Program Files\Git\cmd\git.exe
>path
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\PostgreSQL\pg95\bin;C:\Program Files\Git\cmd
```

But, from QGIS command prompt (osgeo command shell):
```
>git
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Boundless\Desktop\vcredists>path
PATH=C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\apps\qgis\bin;C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\apps\Python27\Scripts;C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\bin;C:\Windows\system32;C:\Windows;C:\Windows\WBem;C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\apps\msys\bin
```

PS: I'm not a windows developer

**Comment by akbargumbira** [comment]
@anitagraser just making sure (it's working in my windows with https), can you try to do:
- Add my test repository with https: ```https://github.com/akbargumbira/qgis_resources_data.git```
- There will be a collection named: "Akbar's Test Collection" and try to install it. 

With git protocol, it needs ssh which on windows does not exist. If this is really the case, we can just make a validation so that users won't be able to use git protocol

**Comment by elpaso** [comment]
I think you should investigate more: I've installed git on windows but is still doesn't work, even if I hardcode the path to the git executable, it still tries to use ssh.

**Comment by anitagraser** [comment]
I'll give it a try once I'm home and at my Win PC.

**Comment by akbargumbira** [comment]
@elpaso it shouldn't need git installed. It needs ssh though when cloning with ssh (with url ```git@repo_url```)

**Comment by anitagraser** [comment]
@akbargumbira 

<pre>import subprocess
subprocess.call('dir')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python27\lib\subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\OSGEO4~1\apps\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\OSGEO4~1\apps\Python27\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
</pre>

**Comment by anitagraser** [comment]
I cannot reproduce the issue anymore today. Installing works fine today. Sorry for the noise.

**Comment by akbargumbira** [comment]
@elpaso I just added logger and get the traceback when failed downloading/installing. It still will install other valid collections in the collection. Which one do you think better?
* Keep this behaviour
* When there is invalid resource in the collection, rollback other resources that are already installed, and give failed status when installing
