### ISSUE TITLE
Design Plugin Toolbar Icon

### ISSUE THREAD

**Issue by anitagraser** [akbargumbira/qgis_resources_sharing#17]
If we keep the toolbar icon, it needs an icon. 

... Thinking about it, maybe it would be best to remove the toolbar and only keep it in the menu - just like Plugin Installer.

**Comment by akbargumbira** [comment]
Agreed, I think we should remove the toolbar. I'll remove it

**Comment by elpaso** [comment]
+1

**Comment by akbargumbira** [comment]
I am closing this. Just changed the icon and remove the plugin from the toolbar. Welcome for any other icons :)
