### ISSUE TITLE
[windows] Add checks for git URIs if git is not availble

### ISSUE THREAD

**Issue by elpaso** [akbargumbira/qgis_resources_sharing#21]
If for some reason (git missing, ssh missing, wrong paths etc.) the collection cannot be fecthed the plugins should warn the user with a suggested solution/workaround (for example: "Install Linux and live happy!")

**Comment by akbargumbira** [comment]
Love the solution! :)

**Comment by akbargumbira** [comment]
I fixed this by using a fallback to use https instead of ssh to clone the repository if it fails using ssh (if the url is ssh anyway)
