### ISSUE TITLE
We need to show the license in the plugin when previewing a collection

### ISSUE THREAD

**Issue by timlinux** [akbargumbira/qgis_resources_sharing#29]

**Comment by akbargumbira** [comment]
Do you think it's enough to allow the author to add one line with option 'license' for that?

**Comment by timlinux** [comment]
Maybe two parts:

License:
License URL:

?

**Comment by akbargumbira** [comment]
ok, that makes sense, going to release a new minor version with some fixes and this!

**Comment by timlinux** [comment]
Thanks dude!

**Comment by akbargumbira** [comment]
@timlinux implemented here https://github.com/akbargumbira/qgis_resources_sharing/commit/2daa4755de66092620b6ccabb0906e31bf6da460 See here for the screencast https://www.youtube.com/watch?v=DxE_PONFsjY (I should probably stop making screencasts :))

**Comment by akbargumbira** [comment]
Closing it now. I will release the new version tomorrow

**Comment by akbargumbira** [comment]
oh no, wrong screencast link https://www.youtube.com/watch?v=RLQsm-s9lH0

**Comment by timlinux** [comment]
Very nice thanks @akbargumbira !
