### ISSUE TITLE
Reloading repositories makes Resource manager forget installed collections

### ISSUE THREAD

**Issue by anitagraser** [akbargumbira/qgis_resources_sharing#34]
To reproduce

1. Install a collection
2. Check that it is listed in the Installed tab
3. Go to Settings and Reload repositories
4. Go back to Installed tab: it is empty

**Comment by akbargumbira** [comment]
Thanks @anitagraser, nice catch! I fixed this in this commit (https://github.com/akbargumbira/qgis_resources_sharing/commit/dad0efe714f4a0c689a2248c5f829ceb584bf008) changing the behaviour.

* When attempting to remove a directory, it will fail and warn users if there are some installed collection from that repository. Users can remove a directory if there is no installed collections from that directory.
* When attempting to update a directory, it will check if there's installed collection from the old URL. Old installed collection exists in the new URL are identified by its register name. Cases for installed collections:
	1. Old collection exists in the new URL, same URL: use the new one, update the status to INSTALLED
	2. Old collection exists in the new URL, different URL: keep them both (add the old one). Because they should be treated as different collection
	3. Old collection doesn't exist in the new URL, same URL: keep the old collection (adding it to new collections)
	4. Old collection doesn't exist in the new URL, different URL: same with 3.
* For the installed collection that the repository URL is not registered in the settings, once it is uninstalled and users reload the repository, it won't be listed in the list of collections

**Comment by akbargumbira** [comment]
I am closing this for now. This will be in the next release
