### ISSUE TITLE
QgsAuthManager is missing in Qgis < 2.12

### ISSUE THREAD

**Issue by LCacheux68224** [akbargumbira/qgis_resources_sharing#36]
Hi, 
I tested the fix #35 in Qgis 2.8, but now the problem is that QgsAuthManager is missing.

**Comment by akbargumbira** [comment]
This should be fixed in the new version. Can you try to upgrade the plugin?

**Comment by LCacheux68224** [comment]
Cool, it seems to work for Qgis 2.8. I continue my tests. 
Thank you for the plugin. It is very useful. 

I tried also the previous versions of Qgis.
It's OK for Qgis 2.4, 2.6, but not for 2.0 and 2.2 because jinja2 is missing.

**Comment by akbargumbira** [comment]
@LCacheux68224 thanks for testing!

Hmm, I think we should just change the metadata then, pretty sure that people are not using QGIS 2.0 and 2.2 anymore :)

**Comment by LCacheux68224** [comment]
No problem for me.
Fortunately we moved from Qgis 2.0 to 2.8 a month ago at work.
Please, don't laugh :-D
