### ISSUE TITLE
Progress bar freezes when downloading collection

### ISSUE THREAD

**Issue by elpaso** [akbargumbira/qgis_resources_sharing#5]
The progress bar remains fixed (does not move).

Try with `QApplication.processEvents() `  in the download loop, if possible.

**Comment by akbargumbira** [comment]
on what system are you on?

**Comment by elpaso** [comment]
Linux Kubuntu 14.04

**Comment by akbargumbira** [comment]
I am sure that this is not happening anymore. I am closing this
