### ISSUE TITLE
Github SSL error

### ISSUE THREAD

**Issue by mstuyts** [akbargumbira/qgis_resources_sharing#54]
When I try to install one of the resources that is on Github, it gives this error:
![resource sharing error](https://user-images.githubusercontent.com/11028014/36896112-9c275db6-1e11-11e8-87eb-cd78de7d751e.jpg)

When I try to install a resource that's on another source, it installs without a problem.

Could this be related to this change on Github? https://githubengineering.com/crypto-removal-notice/

**Comment by nboisteault** [comment]
I have the same error message only with github.

**Comment by crl93116** [comment]
same issue

**Comment by samueltfischer** [comment]
Same issue, can't install any github resource

**Comment by novvier** [comment]
Same issue, can't install any github resource

**Comment by pedrogeo** [comment]
Hi, +1 for this issue.

**Comment by TNick** [comment]
FYI, the directory where the resources can be copied manually in Windows 10 is:
`C:\Users\${USER}\QGIS\Resource Sharing\`

or, more generally:
`${USERPROFILE}\QGIS\Resource Sharing\`

If you would expect it to be in `${USERPROFILE}\.qgis2` that makes two of us.

**Comment by mstuyts** [comment]
In version 0.6.0 of the plugin, this is no longer an issue.  It works just fine.
