### ISSUE TITLE
Not compatible with version 3.0x of QGis

### ISSUE THREAD

**Issue by asitemade4u** [akbargumbira/qgis_resources_sharing#55]
Is there any version of the plugin planned?

**Comment by MarHoff** [comment]
Same wondering here. Is it too hard to port?
Is it planned that it will be superseded by something else?
Should resource sharing projects be abonnoned and replaced by straight-on extensions?

No pressing, I understand it can be pretty though but some guidance would be nice.

**Comment by REIMSMetropole** [comment]
Hi @akbargumbira 
is there any planning for a portage in QG3.x ? i'd be interested.

**Comment by grantboxer** [comment]
I think an upgrade to v3 would be good, as there are some great sets of data and symbols available out there.

**Comment by elpaso** [comment]
Done
